// Force rebuild: 2026-04-29
import type { VercelRequest, VercelResponse } from "@vercel/node";
import { createClient, SupabaseClient } from "@supabase/supabase-js";

// Static export — used as the fallback data source when Supabase is
// unavailable (missing env vars, project paused, RLS misconfig, etc.).
// Bundled into the function deployment via `import` (Vercel/esbuild
// detects JSON imports and includes the file in the function payload).
// The file is regenerated by `npm run registry:export` and committed,
// so the API is always at least as fresh as the last deploy.
import staticBusinesses from "../../data/exports/businesses.json";

const SUPABASE_URL = process.env.SUPABASE_URL || "https://zrrinbeyiuiydalxiwii.supabase.co";
const SUPABASE_SERVICE_KEY = process.env.SUPABASE_SERVICE_ROLE_KEY || "";

let supabase: SupabaseClient;
try {
  supabase = createClient(SUPABASE_URL, SUPABASE_SERVICE_KEY, {
    auth: { autoRefreshToken: false, persistSession: false },
  });
} catch (e) {
  console.error("Failed to create Supabase client:", e);
}

// The static export is already in the public-API shape (name, slug, town,
// townSlug, businessType, etc., with email stripped). No re-transform needed.
// Just type it and pass through.
interface StaticBusiness {
  id: number;
  name: string;
  slug: string;
  category: string;
  businessType: string;
  description: string | null;
  town: string;
  townSlug: string;
  address: string | null;
  phone: string | null;
  website: string | null;
  hours: string | null;
  seasonal: string | null;
  coordinates: { lat: number; lng: number } | null;
  status: string;
  confidence: number;
  social: {
    facebook: string | null;
    instagram: string | null;
    yelp: string | null;
    tripadvisor: string | null;
  };
  memberships?: Record<string, unknown>;
  verifiedLocalBusiness?: boolean;
}

const STATIC_BUSINESSES: StaticBusiness[] = staticBusinesses as StaticBusiness[];

function fallbackResponse(opts: {
  slug?: string;
  town?: string;
  type?: string;
  search?: string;
}): { businesses?: StaticBusiness[]; business?: StaticBusiness } | { error: string; status: number } {
  // Single-slug lookup
  if (opts.slug) {
    const b = STATIC_BUSINESSES.find((x) => x.slug === opts.slug);
    if (!b) return { error: "Business not found", status: 404 };
    return { business: b };
  }

  // List + filters
  let list = STATIC_BUSINESSES;
  if (opts.town) list = list.filter((b) => b.townSlug === opts.town);
  if (opts.type) list = list.filter((b) => b.businessType === opts.type);
  if (opts.search) {
    const q = opts.search.toLowerCase();
    list = list.filter(
      (b) =>
        b.name.toLowerCase().includes(q) ||
        (b.description || "").toLowerCase().includes(q)
    );
  }
  return { businesses: list };
}

/**
 * GET /api/directory/businesses
 *
 * Public API to fetch businesses from Supabase.
 * No authentication required - this is public data.
 * Rate limited to prevent scraping.
 * Email addresses are NOT included (privacy protection).
 *
 * Query params:
 *   - town: filter by town slug
 *   - type: filter by business type slug
 *   - slug: get single business by slug
 *   - search: search by name/description
 */
export default async function handler(req: VercelRequest, res: VercelResponse) {
  // CORS
  res.setHeader("Access-Control-Allow-Origin", "*");
  res.setHeader("Access-Control-Allow-Methods", "GET,OPTIONS");
  res.setHeader("Cache-Control", "s-maxage=60, stale-while-revalidate=300");

  if (req.method === "OPTIONS") {
    return res.status(200).end();
  }

  if (req.method !== "GET") {
    return res.status(405).json({ error: "Method not allowed" });
  }

  const { town, type, slug, search } = req.query;

  // Normalize query parameters once so we can use them in both Supabase and
  // fallback paths.
  const opts = {
    slug: typeof slug === "string" ? slug : undefined,
    town: typeof town === "string" ? town : undefined,
    type: typeof type === "string" ? type : undefined,
    search: typeof search === "string" ? search : undefined,
  };

  // Serve from static export if Supabase isn't initialized (no service key
  // configured, etc.). Static export is bundled into the function payload
  // and is regenerated by `npm run registry:export` at build time.
  if (!supabase) {
    console.warn("Supabase client not initialized — serving static fallback");
    const out = fallbackResponse(opts);
    if ("error" in out) return res.status(out.status).json({ error: out.error });
    res.setHeader("X-Data-Source", "static-fallback");
    return res.status(200).json(out);
  }

  try {
    let query = supabase
      .from("businesses")
      .select("*")
      .eq("business_status", "active")
      .eq("is_duplicate", false)
      .order("business_name");

    // Single business by slug
    if (opts.slug) {
      query = query.eq("slug", opts.slug);
      const { data, error } = await query.single();

      if (error || !data) {
        // Try the static export before 404'ing — handles the case where the
        // business exists in our export but Supabase doesn't (RLS, sync drift).
        const out = fallbackResponse({ slug: opts.slug });
        if ("error" in out) return res.status(out.status).json({ error: out.error });
        res.setHeader("X-Data-Source", "static-fallback");
        return res.status(200).json(out);
      }

      return res.status(200).json({ business: transformBusiness(data) });
    }

    // Filter by town
    if (opts.town) {
      const townName = slugToTownName(opts.town);
      if (townName) query = query.eq("town", townName);
    }

    // Filter by business type
    if (opts.type) {
      const category = slugToCategory(opts.type);
      if (category) query = query.eq("category", category);
    }

    // Search
    if (opts.search) {
      query = query.or(
        `business_name.ilike.%${opts.search}%,short_description.ilike.%${opts.search}%`
      );
    }

    const { data, error } = await query;

    if (error) {
      // Supabase failed (RLS, auth, network, etc.). Serve the static export
      // so the directory keeps working. This was the production state for
      // months in 2026 — the 500 here is what broke prerender and SEO.
      console.error("Supabase error, serving static fallback:", error);
      const out = fallbackResponse(opts);
      if ("error" in out) return res.status(out.status).json({ error: out.error });
      res.setHeader("X-Data-Source", "static-fallback");
      return res.status(200).json(out);
    }

    const businesses = (data || []).map(transformBusiness);

    return res.status(200).json({ businesses });
  } catch (error) {
    // Any other failure (network, JSON parse, etc.) — same fallback strategy.
    console.error("API error, serving static fallback:", error);
    const out = fallbackResponse(opts);
    if ("error" in out) return res.status(out.status).json({ error: out.error });
    res.setHeader("X-Data-Source", "static-fallback");
    return res.status(200).json(out);
  }
}

function transformBusiness(row: Record<string, unknown>) {
  // NOTE: Email is intentionally excluded from public API responses
  // for privacy/anti-scraping protection. Emails are only available
  // through authenticated admin endpoints (/api/admin/businesses).
  return {
    id: row.id,
    name: row.business_name,
    slug: row.slug,
    category: row.category,
    businessType: categoryToSlug(row.category as string),
    description: row.short_description || null,
    town: row.town,
    townSlug: townToSlug(row.town as string),
    address: row.full_address || null,
    phone: row.phone || null,
    // email: REMOVED - not exposed in public API (privacy protection)
    website: row.website || null,
    hours: null,
    seasonal: null,
    coordinates: row.latitude && row.longitude
      ? { lat: row.latitude as number, lng: row.longitude as number }
      : null,
    status: row.business_status || "active",
    confidence: row.confidence_score || 70,
    social: {
      facebook: row.facebook_url || null,
      instagram: row.instagram_url || null,
      yelp: row.yelp_url || null,
      tripadvisor: row.tripadvisor_url || null,
    },
  };
}

function townToSlug(town: string): string {
  if (!town) return "unknown";
  return town.toLowerCase().replace(/\s+/g, "-").replace(/[^a-z0-9-]/g, "");
}

function slugToTownName(slug: string): string | null {
  const townMap: Record<string, string> = {
    "vineyard-haven": "Vineyard Haven",
    "oak-bluffs": "Oak Bluffs",
    "edgartown": "Edgartown",
    "west-tisbury": "West Tisbury",
    "chilmark": "Chilmark",
    "aquinnah": "Aquinnah",
    "menemsha": "Menemsha",
    "tisbury": "Tisbury",
  };
  return townMap[slug] || null;
}

function categoryToSlug(category: string): string {
  if (!category) return "other";

  // Map to exact slugs used in business-types.json
  const categorySlugMap: Record<string, string> = {
    "restaurants, food & beverages": "restaurants-food-beverages",
    "shopping & specialty retail": "shopping-and-specialty-retail",
    "lodging & tourism": "lodging-and-tourism",
    "beauty & wellness": "beauty-and-wellness",
    "arts & entertainment": "arts-and-entertainment",
    "family, community & government": "family-community-government",
    "medical services & providers": "medical-services-and-providers",
    "building & construction": "building-and-construction",
    "business & professional services": "business-and-professional-services",
    "home services & trades": "home-services-and-trades",
    "real estate & rentals": "real-estate-and-rentals",
    "sports & recreation": "sports-and-recreation",
    "transportation & utilities": "transportation-and-utilities",
    "automotive & marine": "automotive-and-marine",
    "wedding & event services": "wedding-and-event-services",
    "banking, finance & insurance": "banking-finance-and-insurance",
    "house, garden & pets": "house-garden-and-pets",
    "professional services": "professional-services",
    "contractors": "contractors",
    "restaurant": "restaurants-food-beverages",
    "other": "other",
  };

  const normalized = category.toLowerCase().trim();
  return categorySlugMap[normalized] || category.toLowerCase()
    .replace(/&/g, "-")
    .replace(/,/g, "")
    .replace(/\s+/g, "-")
    .replace(/[^a-z0-9-]/g, "")
    .replace(/-+/g, "-");
}

function slugToCategory(slug: string): string | null {
  const categoryMap: Record<string, string> = {
    "restaurants-food-beverages": "Restaurants, Food & Beverages",
    "restaurants-food-and-beverages": "Restaurants, Food & Beverages",
    "shopping-specialty-retail": "Shopping & Specialty Retail",
    "shopping-and-specialty-retail": "Shopping & Specialty Retail",
    "professional-services": "Professional Services",
    "building-construction": "Building & Construction",
    "building-and-construction": "Building & Construction",
    "health-wellness": "Health & Wellness",
    "health-and-wellness": "Health & Wellness",
    "arts-entertainment": "Arts & Entertainment",
    "arts-and-entertainment": "Arts & Entertainment",
    "lodging": "Lodging",
    "automotive-marine": "Automotive & Marine",
    "automotive-and-marine": "Automotive & Marine",
    "real-estate": "Real Estate",
    "family-community-government": "Family, Community & Government",
    "contractors": "Contractors",
    "other": "Other",
  };
  return categoryMap[slug] || null;
}
