import { useState, useEffect, useCallback } from 'react';
import type { Business } from '@/data/directory';
import { businesses as staticBusinesses } from '@/data/directory';

// Memberships live in our local SQLite registry, not in Supabase, so the
// Supabase-backed API endpoint can't return them. We augment API responses
// from the static export (loaded by src/data/directory.ts), keyed by slug.
// The static JSON is regenerated by `npm run registry:export` and bundled
// with each deploy, so it's never more than one deploy stale.
//
// `staticBusinesses` starts empty and is populated async by the dynamic
// import in directory.ts. That's fine: the API responses arrive on a similar
// timescale, and on retry the cache will hydrate. For the (rare) case where
// the API returns before the static import resolves, the user still gets
// businesses listed — they just won't see the badge until the static data
// loads, on the next render.
let STATIC_BY_SLUG: Map<string, Business> = new Map();
function refreshIndex() {
  if (STATIC_BY_SLUG.size !== staticBusinesses.length) {
    STATIC_BY_SLUG = new Map(staticBusinesses.map((b) => [b.slug, b]));
  }
}

function hydrateMemberships<T extends { slug?: string; memberships?: unknown; verifiedLocalBusiness?: boolean }>(
  b: T | null | undefined
): T {
  if (!b || !b.slug) return b as T;
  // Trust API-provided memberships if the API ever starts returning them.
  if (b.memberships) return b as T;
  refreshIndex();
  const stat = STATIC_BY_SLUG.get(b.slug);
  if (!stat) return b as T;
  return {
    ...b,
    memberships: stat.memberships,
    verifiedLocalBusiness: stat.verifiedLocalBusiness,
  } as T;
}

interface UseBusinessesOptions {
  town?: string;
  type?: string;
  search?: string;
}

interface UseBusinessesResult {
  businesses: Business[];
  isLoading: boolean;
  error: string | null;
  refetch: () => void;
}

// Global cache
const cache = new Map<string, { data: Business[]; timestamp: number }>();
const CACHE_TTL = 60000; // 1 minute

function getCacheKey(options: UseBusinessesOptions): string {
  return JSON.stringify(options);
}

export function useBusinesses(options: UseBusinessesOptions = {}): UseBusinessesResult {
  const [businesses, setBusinesses] = useState<Business[]>([]);
  const [isLoading, setIsLoading] = useState(true);
  const [error, setError] = useState<string | null>(null);

  const cacheKey = getCacheKey(options);

  const fetchData = useCallback(async () => {
    // Check cache first
    const cached = cache.get(cacheKey);
    if (cached && Date.now() - cached.timestamp < CACHE_TTL) {
      setBusinesses(cached.data);
      setIsLoading(false);
      return;
    }

    setIsLoading(true);
    setError(null);

    try {
      const params = new URLSearchParams();
      if (options.town) params.append('town', options.town);
      if (options.type) params.append('type', options.type);
      if (options.search) params.append('search', options.search);

      const url = `/api/directory/businesses${params.toString() ? `?${params}` : ''}`;
      const response = await fetch(url);

      if (!response.ok) {
        throw new Error('Failed to fetch businesses');
      }

      const data = await response.json();
      const fetchedBusinesses = (data.businesses || []).map(hydrateMemberships);

      // Update cache
      cache.set(cacheKey, { data: fetchedBusinesses, timestamp: Date.now() });

      setBusinesses(fetchedBusinesses);
    } catch (err) {
      setError(err instanceof Error ? err.message : 'Unknown error');
      // Try to use stale cache on error
      const staleCache = cache.get(cacheKey);
      if (staleCache) {
        setBusinesses(staleCache.data);
      }
    } finally {
      setIsLoading(false);
    }
  }, [cacheKey, options.town, options.type, options.search]);

  useEffect(() => {
    fetchData();
  }, [fetchData]);

  return { businesses, isLoading, error, refetch: fetchData };
}

export function useBusiness(slug: string | undefined): {
  business: Business | null;
  isLoading: boolean;
  error: string | null;
  refetch: () => void;
} {
  const [business, setBusiness] = useState<Business | null>(null);
  const [isLoading, setIsLoading] = useState(true);
  const [error, setError] = useState<string | null>(null);

  const fetchData = useCallback(async () => {
    if (!slug) {
      setIsLoading(false);
      return;
    }

    setIsLoading(true);
    setError(null);

    try {
      const response = await fetch(`/api/directory/businesses?slug=${encodeURIComponent(slug)}`);

      if (!response.ok) {
        if (response.status === 404) {
          setError('Business not found');
          setBusiness(null);
          return;
        }
        throw new Error('Failed to fetch business');
      }

      const data = await response.json();
      setBusiness(hydrateMemberships(data.business) || null);
    } catch (err) {
      setError(err instanceof Error ? err.message : 'Unknown error');
    } finally {
      setIsLoading(false);
    }
  }, [slug]);

  useEffect(() => {
    fetchData();
  }, [fetchData]);

  return { business, isLoading, error, refetch: fetchData };
}

// Clear all cached data (call after admin edits)
export function clearBusinessesCache(): void {
  cache.clear();
}

// Hook for featured businesses (high confidence, sorted by name)
export function useFeaturedBusinesses(limit: number = 6): {
  businesses: Business[];
  isLoading: boolean;
  error: string | null;
} {
  const { businesses, isLoading, error } = useBusinesses({});

  // Filter for high-confidence businesses and take the first N
  const featuredBusinesses = businesses
    .filter(b => (b.confidence ?? 70) >= 80)
    .slice(0, limit);

  return { businesses: featuredBusinesses, isLoading, error };
}
